### 验证密码，用户登录（OK）
post http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "user_name": "hahahha01",
  "user_password": "123456"
}

### 用户注册（OK）
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "user_name": "hahahha01",
  "user_password": "123456"
}

### 用户信息接口 验证token
GET http://localhost:4000/api/users/current HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJoYWhhaGhhMDEiLCJpYXQiOjE1ODc0NTM0NTYsImV4cCI6MTU4ODA1ODI1Nn0.HAzqNvvlp1vHdBsxRjhaMPzZ-YmvmrRBDDQjyF0lEwY

### 获取文章列表(OK)
GET http://localhost:4000/api/articles/list HTTP/1.1


### 获取文章内容(OK)
GET http://localhost:4000/api/articles/3 HTTP/1.1


### 提交文章
POST http://localhost:4000/api/articles/submit HTTP/1.1
Content-Type: application/json

{
  "title"   : "测试用文",
  "content" : "今天是个好日子，天气多云转晴，我在开发接口，开发了好几个，希望可以早日上线。",
  "uid"     : "24"
}

### 删除文章
GET http://localhost:4000/api/articles/delete4 HTTP/1.1